# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/lm/Documents/GitHub/etaHEN-SDK

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/lm/Documents/GitHub/etaHEN-SDK

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/lm/Documents/GitHub/etaHEN-SDK/CMakeFiles /mnt/c/Users/lm/Documents/GitHub/etaHEN-SDK//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/lm/Documents/GitHub/etaHEN-SDK/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hijacker

# Build rule for target.
hijacker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hijacker
.PHONY : hijacker

# fast build rule for target.
hijacker/fast:
	$(MAKE) $(MAKESILENT) -f libhijacker/CMakeFiles/hijacker.dir/build.make libhijacker/CMakeFiles/hijacker.dir/build
.PHONY : hijacker/fast

#=============================================================================
# Target rules for targets named util_daemon

# Build rule for target.
util_daemon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 util_daemon
.PHONY : util_daemon

# fast build rule for target.
util_daemon/fast:
	$(MAKE) $(MAKESILENT) -f Plugin_samples/utility_daemon/CMakeFiles/util_daemon.dir/build.make Plugin_samples/utility_daemon/CMakeFiles/util_daemon.dir/build
.PHONY : util_daemon/fast

#=============================================================================
# Target rules for targets named itemzflow_xml_patches

# Build rule for target.
itemzflow_xml_patches: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 itemzflow_xml_patches
.PHONY : itemzflow_xml_patches

# fast build rule for target.
itemzflow_xml_patches/fast:
	$(MAKE) $(MAKESILENT) -f Plugin_samples/itemzflow_xml_patches/CMakeFiles/itemzflow_xml_patches.dir/build.make Plugin_samples/itemzflow_xml_patches/CMakeFiles/itemzflow_xml_patches.dir/build
.PHONY : itemzflow_xml_patches/fast

#=============================================================================
# Target rules for targets named PS5Debug

# Build rule for target.
PS5Debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PS5Debug
.PHONY : PS5Debug

# fast build rule for target.
PS5Debug/fast:
	$(MAKE) $(MAKESILENT) -f Plugin_samples/PS5Debug/CMakeFiles/PS5Debug.dir/build.make Plugin_samples/PS5Debug/CMakeFiles/PS5Debug.dir/build
.PHONY : PS5Debug/fast

#=============================================================================
# Target rules for targets named Game_Plugin_Loader

# Build rule for target.
Game_Plugin_Loader: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Game_Plugin_Loader
.PHONY : Game_Plugin_Loader

# fast build rule for target.
Game_Plugin_Loader/fast:
	$(MAKE) $(MAKESILENT) -f Plugin_samples/Game_Plugin_Loader/CMakeFiles/Game_Plugin_Loader.dir/build.make Plugin_samples/Game_Plugin_Loader/CMakeFiles/Game_Plugin_Loader.dir/build
.PHONY : Game_Plugin_Loader/fast

#=============================================================================
# Target rules for targets named Error_Disabling

# Build rule for target.
Error_Disabling: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Error_Disabling
.PHONY : Error_Disabling

# fast build rule for target.
Error_Disabling/fast:
	$(MAKE) $(MAKESILENT) -f Plugin_samples/Error_Disabling/CMakeFiles/Error_Disabling.dir/build.make Plugin_samples/Error_Disabling/CMakeFiles/Error_Disabling.dir/build
.PHONY : Error_Disabling/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Error_Disabling"
	@echo "... Game_Plugin_Loader"
	@echo "... PS5Debug"
	@echo "... hijacker"
	@echo "... itemzflow_xml_patches"
	@echo "... util_daemon"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

